2025-10-01 09:10:57,134 - INFO - *** Servidor de Calculadora Iniciado ***
2025-10-01 09:11:19,708 - INFO - *** Servidor de Calculadora Iniciado ***
2025-10-01 09:11:21,991 - INFO - *** Servidor de Calculadora Iniciado ***
2025-10-01 09:16:00,690 - INFO - *** Servidor de Calculadora Iniciado ***
2025-10-01 09:21:48,436 - INFO - *** Servidor de Calculadora Iniciado ***
2025-10-01 09:24:42,777 - INFO - *** Servidor de Calculadora Iniciado ***
2025-10-01 09:25:00,240 - INFO - *** Servidor de Calculadora Iniciado ***
2025-10-01 09:25:02,529 - INFO - *** Servidor de Calculadora Iniciado ***
2025-10-01 09:28:36,800 - INFO - *** Servidor de Calculadora Iniciado ***
2025-10-01 09:28:44,737 - INFO - *** Servidor de Calculadora Iniciado ***
2025-10-01 09:28:46,938 - INFO - *** Servidor de Calculadora Iniciado ***
2025-10-01 09:32:18,739 - INFO - *** Servidor de Calculadora Iniciado ***
2025-10-01 09:32:31,616 - INFO - *** Servidor de Calculadora Iniciado ***
2025-10-01 09:32:40,138 - INFO - *** Servidor de Calculadora Iniciado ***
2025-10-01 09:32:42,242 - INFO - *** Servidor de Calculadora Iniciado ***
2025-10-01 09:35:46,661 - INFO - *** Servidor de Calculadora Iniciado ***
2025-10-01 09:35:49,037 - INFO - *** Servidor de Calculadora Iniciado ***
2025-10-01 09:40:01,175 - INFO - *** Servidor de Calculadora Iniciado ***
2025-10-01 09:40:07,584 - INFO - *** Servidor de Calculadora Iniciado ***
2025-10-01 09:50:34,844 - INFO - *** Servidor de Calculadora Iniciado ***
2025-10-01 09:51:02,767 - ERROR - Error al generar el PDF: name 'datetime' is not defined
Traceback (most recent call last):
  File "C:\calculadora_python\app.py", line 106, in exportar_pdf_ruta
    file_name = f"Reporte_de_servicio_{datetime.now().strftime('%d%m%Y%H%M%S')}.pdf"
NameError: name 'datetime' is not defined
2025-10-01 09:51:04,614 - ERROR - Error al generar el PDF: name 'datetime' is not defined
Traceback (most recent call last):
  File "C:\calculadora_python\app.py", line 109, in exportar_pdf_ruta
    file_name = f"Certificado_{datetime.now().strftime('%d%m%Y%H%M%S')}.pdf"
NameError: name 'datetime' is not defined
2025-10-01 09:52:01,816 - INFO - *** Servidor de Calculadora Iniciado ***
2025-10-01 11:55:50,586 - INFO - *** Servidor de Calculadora Iniciado ***
2025-10-01 11:58:52,028 - INFO - *** Servidor de Calculadora Iniciado ***
2025-10-01 14:44:47,516 - INFO - *** Servidor de Calculadora Iniciado ***
2025-10-01 14:44:49,833 - INFO - *** Servidor de Calculadora Iniciado ***
2025-10-01 14:46:00,965 - INFO - *** Servidor de Calculadora Iniciado ***
2025-10-01 14:46:16,200 - INFO - *** Servidor de Calculadora Iniciado ***
2025-10-01 15:24:43,255 - INFO - *** Servidor de Calculadora Iniciado ***
2025-10-01 15:24:45,400 - INFO - *** Servidor de Calculadora Iniciado ***
2025-10-01 15:36:52,303 - INFO - *** Servidor de Calculadora Iniciado ***
2025-10-01 15:36:54,546 - INFO - *** Servidor de Calculadora Iniciado ***
2025-10-01 15:55:11,292 - INFO - *** Servidor de Calculadora Iniciado ***
2025-10-01 15:55:13,563 - INFO - *** Servidor de Calculadora Iniciado ***
2025-10-01 16:07:31,680 - INFO - *** Servidor de Calculadora Iniciado ***
2025-10-01 16:07:33,781 - INFO - *** Servidor de Calculadora Iniciado ***
2025-10-01 16:16:06,252 - INFO - *** Servidor de Calculadora Iniciado ***
2025-10-01 16:16:09,298 - INFO - *** Servidor de Calculadora Iniciado ***
2025-10-01 16:21:16,012 - INFO - *** Servidor de Calculadora Iniciado ***
2025-10-01 16:29:42,731 - INFO - *** Servidor de Calculadora Iniciado ***
2025-10-01 16:29:45,004 - INFO - *** Servidor de Calculadora Iniciado ***
2025-10-01 16:33:21,432 - INFO - *** Servidor de Calculadora Iniciado ***
2025-10-01 16:33:25,487 - INFO - *** Servidor de Calculadora Iniciado ***
2025-10-01 16:33:31,351 - ERROR - Error al generar el PDF: Encountered unknown tag 'endif'.
Traceback (most recent call last):
  File "C:\calculadora_python\app.py", line 117, in exportar_pdf_ruta
    rendered_html = render_template(
  File "C:\Users\gerso\AppData\Roaming\Python\Python310\site-packages\flask\templating.py", line 149, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "C:\Users\gerso\AppData\Roaming\Python\Python310\site-packages\jinja2\environment.py", line 1068, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "C:\Users\gerso\AppData\Roaming\Python\Python310\site-packages\jinja2\environment.py", line 997, in get_template
    return self._load_template(name, globals)
  File "C:\Users\gerso\AppData\Roaming\Python\Python310\site-packages\jinja2\environment.py", line 958, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "C:\Users\gerso\AppData\Roaming\Python\Python310\site-packages\jinja2\loaders.py", line 137, in load
    code = environment.compile(source, name, filename)
  File "C:\Users\gerso\AppData\Roaming\Python\Python310\site-packages\jinja2\environment.py", line 757, in compile
    self.handle_exception(source=source_hint)
  File "C:\Users\gerso\AppData\Roaming\Python\Python310\site-packages\jinja2\environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\calculadora_python\templates\report_template.html", line 93, in <module>
    {% endif %}
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'endif'.
2025-10-01 16:33:34,348 - INFO - *** Servidor de Calculadora Iniciado ***
2025-10-01 16:33:34,827 - ERROR - Error al generar el PDF: Encountered unknown tag 'endif'.
Traceback (most recent call last):
  File "C:\calculadora_python\app.py", line 117, in exportar_pdf_ruta
    rendered_html = render_template(
  File "C:\Users\gerso\AppData\Roaming\Python\Python310\site-packages\flask\templating.py", line 149, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "C:\Users\gerso\AppData\Roaming\Python\Python310\site-packages\jinja2\environment.py", line 1068, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "C:\Users\gerso\AppData\Roaming\Python\Python310\site-packages\jinja2\environment.py", line 997, in get_template
    return self._load_template(name, globals)
  File "C:\Users\gerso\AppData\Roaming\Python\Python310\site-packages\jinja2\environment.py", line 958, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "C:\Users\gerso\AppData\Roaming\Python\Python310\site-packages\jinja2\loaders.py", line 137, in load
    code = environment.compile(source, name, filename)
  File "C:\Users\gerso\AppData\Roaming\Python\Python310\site-packages\jinja2\environment.py", line 757, in compile
    self.handle_exception(source=source_hint)
  File "C:\Users\gerso\AppData\Roaming\Python\Python310\site-packages\jinja2\environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\calculadora_python\templates\report_template.html", line 93, in <module>
    {% endif %}
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'endif'.
2025-10-01 16:33:38,950 - ERROR - Error al generar el PDF: Encountered unknown tag 'endif'.
Traceback (most recent call last):
  File "C:\calculadora_python\app.py", line 117, in exportar_pdf_ruta
    rendered_html = render_template(
  File "C:\Users\gerso\AppData\Roaming\Python\Python310\site-packages\flask\templating.py", line 149, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "C:\Users\gerso\AppData\Roaming\Python\Python310\site-packages\jinja2\environment.py", line 1068, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "C:\Users\gerso\AppData\Roaming\Python\Python310\site-packages\jinja2\environment.py", line 997, in get_template
    return self._load_template(name, globals)
  File "C:\Users\gerso\AppData\Roaming\Python\Python310\site-packages\jinja2\environment.py", line 958, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "C:\Users\gerso\AppData\Roaming\Python\Python310\site-packages\jinja2\loaders.py", line 137, in load
    code = environment.compile(source, name, filename)
  File "C:\Users\gerso\AppData\Roaming\Python\Python310\site-packages\jinja2\environment.py", line 757, in compile
    self.handle_exception(source=source_hint)
  File "C:\Users\gerso\AppData\Roaming\Python\Python310\site-packages\jinja2\environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\calculadora_python\templates\report_template.html", line 93, in <module>
    {% endif %}
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'endif'.
2025-10-01 16:33:53,081 - ERROR - Error al generar el PDF: Encountered unknown tag 'endif'.
Traceback (most recent call last):
  File "C:\calculadora_python\app.py", line 117, in exportar_pdf_ruta
    rendered_html = render_template(
  File "C:\Users\gerso\AppData\Roaming\Python\Python310\site-packages\flask\templating.py", line 149, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "C:\Users\gerso\AppData\Roaming\Python\Python310\site-packages\jinja2\environment.py", line 1068, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "C:\Users\gerso\AppData\Roaming\Python\Python310\site-packages\jinja2\environment.py", line 997, in get_template
    return self._load_template(name, globals)
  File "C:\Users\gerso\AppData\Roaming\Python\Python310\site-packages\jinja2\environment.py", line 958, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "C:\Users\gerso\AppData\Roaming\Python\Python310\site-packages\jinja2\loaders.py", line 137, in load
    code = environment.compile(source, name, filename)
  File "C:\Users\gerso\AppData\Roaming\Python\Python310\site-packages\jinja2\environment.py", line 757, in compile
    self.handle_exception(source=source_hint)
  File "C:\Users\gerso\AppData\Roaming\Python\Python310\site-packages\jinja2\environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\calculadora_python\templates\report_template.html", line 93, in <module>
    {% endif %}
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'endif'.
2025-10-01 16:35:41,734 - INFO - *** Servidor de Calculadora Iniciado ***
2025-10-01 16:35:44,719 - INFO - *** Servidor de Calculadora Iniciado ***
2025-10-01 16:42:03,362 - INFO - *** Servidor de Calculadora Iniciado ***
2025-10-01 16:42:06,743 - INFO - *** Servidor de Calculadora Iniciado ***
2025-10-01 16:43:27,189 - INFO - *** Servidor de Calculadora Iniciado ***
2025-10-01 16:47:55,280 - INFO - *** Servidor de Calculadora Iniciado ***
2025-10-01 16:48:12,663 - INFO - *** Servidor de Calculadora Iniciado ***
2025-10-01 16:48:27,401 - INFO - *** Servidor de Calculadora Iniciado ***
2025-10-01 16:48:29,462 - INFO - *** Servidor de Calculadora Iniciado ***
2025-10-01 16:56:02,810 - INFO - *** Servidor de Calculadora Iniciado ***
2025-10-01 16:56:05,163 - INFO - *** Servidor de Calculadora Iniciado ***
2025-10-01 17:49:15,415 - INFO - *** Servidor de Calculadora Iniciado ***
2025-10-01 17:49:17,690 - INFO - *** Servidor de Calculadora Iniciado ***
2025-10-01 17:55:53,116 - INFO - *** Servidor de Calculadora Iniciado ***
2025-10-01 17:55:55,249 - INFO - *** Servidor de Calculadora Iniciado ***
